name: Go

on:
  push:
    branches: [ "dev" ]
    tags:
      - "v*"

env:
  APP: ${{ github.event.repository.name }}
  IMAGE_NAME: eria/${{ github.event.repository.name }}
  REGISTRY: rg.fr-par.scw.cloud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Git ENV
      shell: bash
      run: |
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Generate TAGS (stable)
      if: github.ref_type == 'tag'
      shell: bash
      run: |
        echo "TAG1=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
        echo "TAG2=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}" >> $GITHUB_ENV

    - name: Generate TAGS (dev)
      if: github.ref_type != 'tag'
      shell: bash
      run: |
        echo "TAG1=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev" >> $GITHUB_ENV
        echo "TAG2=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA_SHORT }}-${{ env.BRANCH }}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2
  
    - name: Login to Docker Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}

    - name: Show GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Build && Push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm/v7,linux/arm/v6,linux/amd64,linux/arm64
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.TAG1 }}
          ${{ env.TAG2 }}
  
    - name: Show details of image in the registry
      run: |
        docker buildx imagetools inspect "${{ env.TAG1 }}"
